export enum NotificationType {
  ARTICLE_LIKED = 'ARTICLE_LIKED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  REPLY_ADDED = 'REPLY_ADDED',
  COMMENT_LIKED = 'COMMENT_LIKED',
  ARTICLE_SAVED = 'ARTICLE_SAVED',
}
